title: yude.jp
email: admin@yude.jp
description: >-
  yude.jp のトップページです。
baseurl: "/"
url: "https://www.yude.jp"
twitter_username: yude_jp
github_username: yude
include: [_pages]

theme: minima
plugins:
  - jekyll-feed
  - jekyll-email-protect
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:year-:month-:title

github: [metadata]
